In [16]:
import pandas as pd
import random

In [17]:
st = chr(71)  #48 --> 0 , 65 --> A and 97 --> a

'Z'

In [29]:
data = [ [f"{chr(random.randrange(65,91))} {chr(random.randrange(48,58))} {chr(random.randrange(97 , 123))}" , i] for i in range(1,1001)]

In [30]:
df = pd.DataFrame(data , columns=["characters","number"] )
df.head()

  characters  number
0      M 0 l       1
1      O 3 d       2
2      R 5 o       3
3      O 1 z       4
4      O 4 v       5

In [31]:
df.describe()

            number
count  1000.000000
mean    500.500000
std     288.819436
min       1.000000
25%     250.750000
50%     500.500000
75%     750.250000
max    1000.000000